### ISSUE TITLE
TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by KIC-Crack** [rg2/DeepFluoroLabeling-IPCAI2020#1]
Hi,

Thanks for providing such a great code！
I am passing the following command
`python -u train.py ipcai_2020_ds_8x.h5 --train-pats 2,3,4,5,6 --num-classes 7 --init-lr 0.1 --momentum 0.9 --unet-batch-norm --unet- no-max-pool --unet-img-dim 192 --unet-num-lvls 6 --batch-size 5 --max-num-epochs 500 --unet-init-feats-exp 5 --wgt-decay 0.0001 --data-aug --unet-padding --nesterov --checkpoint-net yy_check_net.pt --checkpoint-freq 100 --use-lands --best-net yy_best_net.pt --lr-sched plateau --train -valid-split 0.85 --train-loss-txt yy_train_loss.txt --valid-loss-txt yy_valid_loss.txt --heat-coeff 0.5`
When running the training code, it throws an error
```python
num. lands read from file: 14
initializing training dataset/dataloader
split dataset into train/validation
  randomly splitting all complete tensors into training/validation...
Length of training dataset: 217
Length of validation dataset: 38
creating network
moving network to device...
creating loss function
  Dice + Heatmap Loss...
creating SGD optimizer and LR scheduler
Start Training...
Epoch: 000
/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torchvision/transforms/functional.py:1041: UserWarning: Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead
  "Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead"
/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torchvision/transforms/functional.py:1041: UserWarning: Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead
  "Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead"
/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torchvision/transforms/functional.py:1041: UserWarning: Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead
  "Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead"
/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torchvision/transforms/functional.py:1041: UserWarning: Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead
  "Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead"
/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torchvision/transforms/functional.py:1041: UserWarning: Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead
  "Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead"
/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torchvision/transforms/functional.py:1041: UserWarning: Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead
  "Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead"
/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torchvision/transforms/functional.py:1041: UserWarning: Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead
  "Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead"
/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torchvision/transforms/functional.py:1041: UserWarning: Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead
  "Argument resample is deprecated and will be removed since v0.10.0. Please, use interpolation instead"
Traceback (most recent call last):
  File "train.py", line 399, in <module>
    for (i, data) in enumerate(train_dl, 0):
  File "/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/***/Downloads/DeepFluoroLabeling-IPCAI2020-2020.03.17/train_test_code/dataset.py", line 230, in __getitem__
    A_inv = TF._get_inverse_affine_matrix(center_of_rot, rot_ang, (trans_x, trans_y), scale_factor, shear)
  File "/home/***/anaconda3/envs/re/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 903, in _get_inverse_affine_matrix
    sx, sy = [math.radians(s) for s in shear]
TypeError: 'float' object is not iterable
```

Can you help me？

Thanks in advance,
Crack

**Comment by rg2** [comment]
Thanks for the comment @KIC-Crack . Can you provide some details on your setup so I can try and replicate? e.g. pytorch version, python version, operating system, etc.

I have not run this code since pytorch 1.2, so my guess is that in newer versions `TF._get_inverse_affine_matrix` is now expecting the shear parameter to have two values instead of a single float.

**Comment by rg2** [comment]
Hi @KIC-Crack . I have fixed this issue in the latest master. Please reopen this issue if it still does not work for you. Thanks!
